apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: allmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: product-service
          image: 646596232446.dkr.ecr.ap-northeast-2.amazonaws.com/product-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: CONFIG_SERVER_URI
              value: "http://config-server:8888"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "10.0.1.146:19092,10.0.1.146:19093,10.0.1.146:19094"
            - name: DB_HOST
              value: "10.0.1.90"
            - name: DB_PORT
              value: "3310"
            - name: DB_NAME
              value: "productdb"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: product-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-db-secret
                  key: password
            - name: AWS_S3_BUCKET
              value: "allmart-product-images"
            - name: AWS_REGION
              value: "ap-northeast-2"
            - name: S3_BUCKET
              value: "allmart-product-images"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: ANTHROPIC_API_KEY
              value: ""
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service:8085"
            - name: TEMPO_ENDPOINT
              value: "http://43.200.2.221:4318/v1/traces"
            - name: LOKI_URL
              value: "http://43.200.2.221:3100/loki/api/v1/push"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 200
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 200
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: allmart
spec:
  selector:
    app: product-service
  ports:
    - port: 8083
      targetPort: 8083
